### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by agung2001** [lhsazevedo/duplicati-ui#3]
m not sure for some reason I can't run the project : `npm run serve` show this error 
```
npm ERR! Missing script: "serve"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/muhammadsundoro/.npm/_logs/2024-04-11T02_13_36_752Z-debug-0.log
```

I think you're missing `serve` script on [package.json#L5-L10](https://github.com/lhsazevedo/duplicati-ui/blob/d0782f4f7acb9a6bc1c5907491e58b7c9c566ea6/package.json#L5-L10)
or maybe what you mean is `npm run dev`?

**Comment by lhsazevedo** [comment]
Yup, thanks for pointing out. The requirements got outdated after the upgrade from Vue CLI to Vite (See #2).
